project:
  type: website
  output-dir: docs

website:
  title: "Public Opinion and Policy"
  navbar:
    right:
      - syllabus.qmd

  page-footer:
      border: false
      left: © 2023 Gustavo Diaz
      right: Powered by [{{< fa brands r-project >}}](https://cran.r-project.org/) and [Quarto](https://quarto.org/)
  

format:
  html:
    theme: 
      - litera
      - custom.scss



