project:
  type: website
  output-dir: docs

website:
  title: "Public Opinion and Policy"
  navbar:
    right:
      - syllabus.qmd
      - schedule.qmd
      - assignments.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Labs"
        file: labs/index.qmd
      - text: "Resources"
        file: resources/index.qmd
      - text: "Avenue"
        href: "https://avenue.mcmaster.ca/"
      - icon: cloud-fill
        href: "https://posit.cloud/"
        aria-label: Posit.cloud
      

  page-footer:
      border: false
      left: © 2023 Gustavo Diaz
      right: Powered by [{{< fa brands r-project >}}](https://cran.r-project.org/) and [Quarto](https://quarto.org/)
  

format:
  html:
    theme: 
      - litera
      - custom.scss



