project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!labs/"
  resources:
    - "slides/"
    - "labs/*.Rmd"
  
# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Public Opinion and Policy"
  navbar:
    right:
      - syllabus.qmd
      - schedule.qmd
      - assignments.qmd
      - text: "Content"
        file: content/index.qmd
      - resources.qmd
      - text: "Avenue"
        href: "https://avenue.mcmaster.ca/"
      - icon: cloud-fill
        href: "https://posit.cloud/"
        aria-label: Posit.cloud
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      contents:
        - section: "Course content"
          contents:
            - content/index.qmd
            - text: "1. Introduction"
              file: content/01_content.qmd
            - text: "2. Representative surveys"
              file: content/02_content.qmd
            - text: "3. Panel surveys"
              file: content/03_content.qmd
            - text: "4. Sensitive questions"
              file: content/04_content.qmd
            - text: "5. Survey experiments"
              file: content/05_content.qmd
            - text: "6. Convenience samples"
              file: content/06_content.qmd
            - text: "8. Evidence-informed policy"
              file: content/08_content.qmd
            - text: "9. Field experiments I"
              file: content/09_content.qmd
            - text: "10. Field experiments II"
              file: content/10_content.qmd
            - text: "11. Beyond experimentation"
              file: content/11_content.qmd
            - text: "12. Quasi-experiments I"
              file: content/12_content.qmd
            - text: "13. Quasi-experiments II"
              file: content/13_content.qmd
            - text: "14. Flex class or open lab"
              file: content/14_content.qmd
      

  page-footer:
      border: false
      left: © 2023 Gustavo Diaz
      right: Powered by [{{< fa brands r-project >}}](https://cran.r-project.org/) and [Quarto](https://quarto.org/)
  

format:
  html:
    theme: 
      - litera
      - custom.scss



